### ISSUE TITLE
cmake build does not work as intended for this specific module

### ISSUE THREAD

**Issue by ilovecoding294786** [davidonete/cmangos-trainingdummies#1]
-- Build trainingdummies Module : No (default)
-- Build paladinpower Module : No (default)
-- Build extractors      : No  (default)
-- Build RecastDemoMod   : No  (default)
-- Build git_id          : No  (default)
-- Link-time optimizations : No  (default)
-- Target directory for dev binaries(DEV_BINARY_DIR) = /home/cmangos/cmangos/build/UILD_MODULE_TRAININGDUMMIES=ON

-- Build files have been written to: /home/cmangos/cmangos/build/UILD_MODULE_TRAININGDUMMIES=ON
root@cmangos:/home/cmangos/cmangos/build# ls
 CMakeCache.txt   cmake_install.cmake     contrib   _deps         install_manifest.txt   src
 CMakeFiles       cmake_uninstall.cmake   dep       gdbcommands   Makefile              'UILD_MODULE_TRAININGDUMMIES=ON'

Above shows build files were written in build directory instead of the core src folder where it suppose to be like other modules, however it was built under build folder with weird name syntax'ed by name of " 'UILD_MODULE_TRAININGDUMMIES=ON' ".
I ran cmake using this command and made sure that BUILD_MODULE_TRAININGDUMMIES is active

cmake ../mangos -DCMAKE_INSTALL_PREFIX=/home/cmangos/cmangos/run -DPCH=1 -DBUILD_MODULES=ON -BUILD_MODULE_TRAININGDUMMIES=ON

Also during build the list does not show "Yes" for this module >> -- Build trainingdummies Module : No (default)

**Comment by flekz-games** [comment]
Looks like the cmake command had some weird issues when executing on your machine. Try setting the paths of directories between quotes. This is not a module issue, just a command syntax issue. I'm not a cmake expert so I can't help much on that regard.

If it helps this is what I usually use on my server machine to execute cmake:
`cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_FLAGS="-Wno-switch -Wno-format -Wno-format-security -Wno-format-extra-args -Wno-unused-value -O0 -g" -DCMAKE_CXX_FLAGS="-Wno-switch -Wno-format -Wno-format-security -Wno-format-extra-args -Wno-unused-value -O0 -g" -DCMAKE_INSTALL_PREFIX=/opt/cmangos -DBUILD_LOGIN_SERVER=OFF -DBUILD_GAME_SERVER=ON -DBUILD_SCRIPTDEV=ON -DPCH=ON -DBUILD_AHBOT=ON -DBUILD_PLAYERBOTS=ON -DBUILD_MODULES=ON -DBUILD_MODULE_ACHIEVEMENTS=ON -DBUILD_MODULE_IMMERSIVE=ON -DBUILD_MODULE_HARDCORE=ON -DBUILD_MODULE_TRANSMOG=ON -DBUILD_MODULE_DUALSPEC=ON -DBUILD_MODULE_TRAININGDUMMIES=ON`

**Comment by ilovecoding294786** [comment]
bro i was using -BUILD_MODULE_TRAININGDUMMIES instead of -DBUILD_MODULE_TRAININGDUMMIES :/. i copy paste it from readme on each of the module so it was missing the "D" please edit it cause it got me scratching my head alot :P. maan it took me hours to figure out whats wrong and when i built it this way cmake installed zlib for that module and it messed up the whole setup, becareful a typo like that will ruin the whole setup in build directory

**Comment by flekz-games** [comment]
The readme instructions are correct, the "D" is a prefix needed for cmake command but not needed for UI based cmake for example. I can add a note to clarify, but that is basic cmake knowledge...

An example can also be found here https://github.com/davidonete/cmangos-modules?tab=readme-ov-file#how-to-install

**Comment by ilovecoding294786** [comment]
now i can go buy my coffee and eat my croissant without worrying about a nested cpp bug :D
